import Head from 'next/head'
import { Inter } from '@next/font/google'
import Header from '../components/Header'
import Login from '../components/Login'
import { useSession,} from "next-auth/react"
import Sidebar from '../components/Sidebar.js'
import Feed from '../components/Feed.js'
import Widgets from '../components/Widgets'


const inter = Inter({ subsets: ['latin'] })

const Home = () => {
  const session = useSession();
  console.log(session);

try { 
    if (session.status=='unauthenticated') {
      return (
        <>
          <Login />
        </>
      )
    } 
}  catch(e) { 
    console.log(e);
  }
 

  return (
    <div className='h-screen overflow-hidden bg-gray-100'>
      <Head>
        <title>Socials</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className='flex'>
        {/* Sidebar */}
        <Sidebar />
        {/* Feed */}
        <Feed />
        {/* Widgets */}
        <Widgets />
      </main>
    </div>
  )
  

} 

export default Home;
