import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Header from '../components/Header'
import Login from '../components/Login'
import { useSession,} from "next-auth/react"
import Sidebar from '../components/Sidebar'


const inter = Inter({ subsets: ['latin'] })

const Home = () => {
  const session = useSession();
  console.log(session);

try { 
    if (session.status=='unauthenticated') {
      return (
        <>
          <Login />
        </>
      )
    } 
}  catch(e) { 
    console.log(e);
  }
 

  return (
    <>
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        {/* Sidebar */}
        <Sidebar />
        {/* Feed */}
        {/* Widgets */}
      </main>
    </>
  )
  

} 

export default Home;
